#!/usr/bin/python3

import pyasicam as pc

print("Number of cameras:", pc.GetNumOfConnectedCameras())
print("Supported PIDs:", pc.GetProductIDs())
print("SDK version:", pc.GetSDKVersion())
c = pc.Camera(0)
prop = c.GetCameraProperty()
print("Name:", prop.Name)
print("Pixel size:", prop.PixelSize)
print("e/DN:", prop.ElecPerADU)
print("bit depth:", prop.BitDepth)
c.OpenCamera()
c.InitCamera()
print("is triggercam:", prop.IsTriggerCam)
for i in range(c.GetNumOfControls()):
    cap = c.GetControlCaps(i)
    (val, auto) = c.GetControlValue(i)
    print(cap.Name, cap.Description, val, auto)
print("gain:", c.GetControlValue(pc.GAIN))
c.SetControlValue(pc.GAIN, 10, False)
print("gain:", c.GetControlValue(pc.GAIN))
c.SetControlValue(pc.GAIN, 20, False)
print("gain:", c.GetControlValue(pc.GAIN))
print("ROI:", c.GetROIFormat())
c.SetROIFormat(256, 256, 2, pc.IMG_RGB24)
print("ROI:", c.GetROIFormat())
c.SetROIFormat(512, 512, 1, pc.IMG_RAW8)
print("ROI:", c.GetROIFormat())
print("Start:", c.GetStartPos())
c.SetStartPos(16, 16)
print("Start:", c.GetStartPos())
c.SetStartPos(32, 32)
print("Start:", c.GetStartPos())
print("Dropped:", c.GetDroppedFrames())
c.SetControlValue(pc.EXPOSURE, 1000000, False)
print("exposure:", c.GetControlValue(pc.EXPOSURE))
c.StartVideoCapture()
img = c.GetVideoData(-1)
print("shape:", img.shape)
c.StopVideoCapture()
c.PulseGuideOn(pc.GUIDE_NORTH)
c.PulseGuideOff(pc.GUIDE_NORTH)
c.StartExposure(False)
while c.GetExpStatus() != pc.EXP_SUCCESS:
    pass
c.StopExposure()
img = c.GetDataAfterExp()
print("shape:", img.shape)
# print("id:", c.GetID())
print("offsets/gain:", c.GetGainOffset())
c.CloseCamera()
